let users=[{"id":1,"name":"Tessa","email":"tthibodeaux0@delicious.com","gender":"Female","location":"Colombia"},
    {"id":2,"name":"Douglas","email":"doller1@shareasale.com","gender":"Male","location":"China"},
    {"id":3,"name":"Barnaby","email":"bdenham2@cbsnews.com","gender":"Male","location":"Germany"},
    {"id":4,"name":"Marietta","email":"mreddihough3@sohu.com","gender":"Female","location":"Indonesia"},
    {"id":5,"name":"Roddie","email":"rgoldspink4@gizmodo.com","gender":"Polygender","location":"Philippines"},
    {"id":6,"name":"Suzanne","email":"spatkin5@cbsnews.com","gender":"Female","location":"Russia"},
    {"id":7,"name":"Kendra","email":"kbondesen6@nba.com","gender":"Female","location":"United States"},
    {"id":8,"name":"Sylvan","email":"shardiker7@technorati.com","gender":"Male","location":"Bangladesh"},
    {"id":9,"name":"Phil","email":"plinstead8@phpbb.com","gender":"Female","location":"South Africa"},
    {"id":10,"name":"Krystle","email":"kdinneges9@1und1.de","gender":"Female","location":"Indonesia"},
    {"id":11,"name":"Nadya","email":"ngerrita@ucsd.edu","gender":"Female","location":"Ukraine"},
    {"id":12,"name":"Davin","email":"dkeirleb@stumbleupon.com","gender":"Male","location":"Guatemala"},
    {"id":13,"name":"Kelsey","email":"kpalphramandc@360.cn","gender":"Female","location":"Slovenia"},
    {"id":14,"name":"Francois","email":"fcavilled@blogspot.com","gender":"Male","location":"China"},
    {"id":15,"name":"Matias","email":"msillimane@ed.gov","gender":"Male","location":"China"},
    {"id":16,"name":"Ethan","email":"edemef@xing.com","gender":"Male","location":"Portugal"},
    {"id":17,"name":"Minor","email":"mgawkesg@archive.org","gender":"Male","location":"Brazil"},
    {"id":18,"name":"Cary","email":"cbradborneh@multiply.com","gender":"Male","location":"Russia"},
    {"id":19,"name":"Jourdan","email":"jwalickii@yale.edu","gender":"Female","location":"Nigeria"},
    {"id":20,"name":"Lorri","email":"ldeningtonj@51.la","gender":"Female","location":"China"},
    {"id":21,"name":"Burty","email":"bdockertyk@nytimes.com","gender":"Male","location":"Argentina"},
    {"id":22,"name":"Elysha","email":"ekristofl@phoca.cz","gender":"Female","location":"China"},
    {"id":23,"name":"Elmore","email":"egoodym@360.cn","gender":"Male","location":"Australia"},
    {"id":24,"name":"Merilyn","email":"mbruggemann@php.net","gender":"Female","location":"Philippines"},
    {"id":25,"name":"Alon","email":"apereirao@furl.net","gender":"Male","location":"Thailand"},
    {"id":26,"name":"Say","email":"sbilamp@independent.co.uk","gender":"Male","location":"Indonesia"},
    {"id":27,"name":"Skip","email":"srutiglianoq@theglobeandmail.com","gender":"Non-binary","location":"Serbia"},
    {"id":28,"name":"Kara","email":"kdaffernr@scribd.com","gender":"Female","location":"Portugal"},
    {"id":29,"name":"Allianora","email":"aquestes@cbsnews.com","gender":"Female","location":"Czech Republic"},
    {"id":30,"name":"Starr","email":"sbeazet@pinterest.com","gender":"Female","location":"Bolivia"},
    {"id":31,"name":"Alejandra","email":"aaldissu@tmall.com","gender":"Female","location":"Mexico"},
    {"id":32,"name":"Jenna","email":"jmatokhninv@reverbnation.com","gender":"Genderqueer","location":"Portugal"},
    {"id":33,"name":"Marcela","email":"mhackfordw@census.gov","gender":"Agender","location":"Russia"},
    {"id":34,"name":"Elnore","email":"eruddx@youtube.com","gender":"Female","location":"Indonesia"},
    {"id":35,"name":"Ive","email":"itoony@linkedin.com","gender":"Male","location":"Indonesia"},
    {"id":36,"name":"Hardy","email":"hsotheronz@shutterfly.com","gender":"Male","location":"Macedonia"},
    {"id":37,"name":"Jacklin","email":"jpfeffel10@wunderground.com","gender":"Female","location":"Indonesia"},
    {"id":38,"name":"Nancie","email":"nschachter11@shop-pro.jp","gender":"Female","location":"Russia"},
    {"id":39,"name":"Nickey","email":"nlong12@is.gd","gender":"Male","location":"China"},
    {"id":40,"name":"Laurence","email":"llees13@skype.com","gender":"Male","location":"Argentina"},
    {"id":41,"name":"Regina","email":"rtune14@arstechnica.com","gender":"Female","location":"Macedonia"},
    {"id":42,"name":"Petronille","email":"pcruft15@quantcast.com","gender":"Female","location":"Malaysia"},
    {"id":43,"name":"Nikolai","email":"ngadsden16@aboutads.info","gender":"Male","location":"Belarus"},
    {"id":44,"name":"Lazar","email":"lbegwell17@sitemeter.com","gender":"Male","location":"Indonesia"},
    {"id":45,"name":"Clarita","email":"ccollyer18@privacy.gov.au","gender":"Female","location":"United States"},
    {"id":46,"name":"Massimiliano","email":"mmant19@clickbank.net","gender":"Male","location":"Bosnia and Herzegovina"},
    {"id":47,"name":"Deeyn","email":"dcockman1a@china.com.cn","gender":"Female","location":"Iran"},
    {"id":48,"name":"Dari","email":"dpereira1b@weather.com","gender":"Female","location":"Brazil"},
    {"id":49,"name":"Nikolas","email":"nheyworth1c@businessinsider.com","gender":"Male","location":"China"},
    {"id":50,"name":"Gavra","email":"gnail1d@cbc.ca","gender":"Female","location":"Indonesia"},
    {"id":51,"name":"Michele","email":"mpreator1e@over-blog.com","gender":"Male","location":"Chile"},
    {"id":52,"name":"Kane","email":"ksprull1f@devhub.com","gender":"Male","location":"Cuba"},
    {"id":53,"name":"Jana","email":"jbakey1g@jalbum.net","gender":"Female","location":"Poland"},
    {"id":54,"name":"Nappie","email":"naxworthy1h@nba.com","gender":"Male","location":"Tanzania"},
    {"id":55,"name":"Rosy","email":"rmctavish1i@vk.com","gender":"Female","location":"Greece"},
    {"id":56,"name":"Wolfgang","email":"wcole1j@joomla.org","gender":"Male","location":"China"},
    {"id":57,"name":"Lurline","email":"lbauckham1k@example.com","gender":"Female","location":"China"},
    {"id":58,"name":"Hermon","email":"hpigram1l@ovh.net","gender":"Non-binary","location":"Japan"},
    {"id":59,"name":"Daryl","email":"dtrevaskis1m@com.com","gender":"Male","location":"China"},
    {"id":60,"name":"Chev","email":"cmargrett1n@cnbc.com","gender":"Male","location":"Bahamas"},
    {"id":61,"name":"Bonny","email":"bsyncke1o@lycos.com","gender":"Female","location":"Indonesia"},
    {"id":62,"name":"Kaleb","email":"kjotcham1p@hhs.gov","gender":"Male","location":"China"},
    {"id":63,"name":"Morten","email":"mgreder1q@i2i.jp","gender":"Male","location":"Philippines"},
    {"id":64,"name":"Cindra","email":"cleades1r@youku.com","gender":"Female","location":"Hungary"},
    {"id":65,"name":"Elliott","email":"ebelamy1s@reddit.com","gender":"Male","location":"France"},
    {"id":66,"name":"Doroteya","email":"dmckearnen1t@eventbrite.com","gender":"Female","location":"Denmark"},
    {"id":67,"name":"Imogen","email":"iwandrey1u@addtoany.com","gender":"Female","location":"Indonesia"},
    {"id":68,"name":"Trace","email":"tlahrs1v@thetimes.co.uk","gender":"Male","location":"Uganda"},
    {"id":69,"name":"Obediah","email":"oglauber1w@hubpages.com","gender":"Male","location":"Argentina"},
    {"id":70,"name":"Fiona","email":"feuston1x@wordpress.org","gender":"Female","location":"Japan"},
    {"id":71,"name":"Arliene","email":"agorce1y@linkedin.com","gender":"Female","location":"Mauritius"},
    {"id":72,"name":"Griffin","email":"greinhart1z@examiner.com","gender":"Male","location":"Sweden"},
    {"id":73,"name":"Josiah","email":"jpywell20@studiopress.com","gender":"Non-binary","location":"Chile"},
    {"id":74,"name":"Perrine","email":"pwarrier21@yahoo.com","gender":"Female","location":"Vietnam"},
    {"id":75,"name":"Bonnie","email":"bkindall22@eepurl.com","gender":"Female","location":"Indonesia"},
    {"id":76,"name":"Desi","email":"dthomton23@sun.com","gender":"Male","location":"Peru"},
    {"id":77,"name":"Binni","email":"bstreat24@webmd.com","gender":"Female","location":"China"},
    {"id":78,"name":"Cindelyn","email":"chenkens25@goo.gl","gender":"Female","location":"Kenya"},
    {"id":79,"name":"Clarie","email":"ccattonnet26@devhub.com","gender":"Female","location":"Philippines"},
    {"id":80,"name":"Lisabeth","email":"lfishbourne27@netvibes.com","gender":"Female","location":"Palestinian Territory"},
    {"id":81,"name":"Marylinda","email":"mreynolds28@adobe.com","gender":"Female","location":"Mongolia"},
    {"id":82,"name":"Barnabe","email":"bhoffman29@wsj.com","gender":"Male","location":"France"},
    {"id":83,"name":"Jocelyne","email":"jepinay2a@sohu.com","gender":"Female","location":"Greece"},
    {"id":84,"name":"Glennis","email":"gfipp2b@barnesandnoble.com","gender":"Non-binary","location":"China"},
    {"id":85,"name":"Catherina","email":"ctudge2c@foxnews.com","gender":"Female","location":"Indonesia"},
    {"id":86,"name":"Elvis","email":"ekamiyama2d@free.fr","gender":"Male","location":"Canada"},
    {"id":87,"name":"Fonz","email":"fstancer2e@desdev.cn","gender":"Male","location":"Macedonia"},
    {"id":88,"name":"Sal","email":"sfinneran2f@de.vu","gender":"Female","location":"Indonesia"},
    {"id":89,"name":"Brunhilde","email":"bnoar2g@harvard.edu","gender":"Female","location":"Jamaica"},
    {"id":90,"name":"Jarid","email":"jchiechio2h@ning.com","gender":"Agender","location":"Indonesia"},
    {"id":91,"name":"Hildegaard","email":"haxelby2i@auda.org.au","gender":"Female","location":"Bulgaria"},
    {"id":92,"name":"Jonell","email":"jrumney2j@auda.org.au","gender":"Female","location":"Indonesia"},
    {"id":93,"name":"Ophelia","email":"olongmaid2k@squarespace.com","gender":"Polygender","location":"Canada"},
    {"id":94,"name":"Evania","email":"egrigg2l@cocolog-nifty.com","gender":"Female","location":"Philippines"},
    {"id":95,"name":"Domenico","email":"dworsnip2m@mac.com","gender":"Male","location":"Sweden"},
    {"id":96,"name":"Beret","email":"bcargon2n@forbes.com","gender":"Female","location":"United Arab Emirates"},
    {"id":97,"name":"Tyrone","email":"tcastells2o@cnet.com","gender":"Male","location":"China"},
    {"id":98,"name":"Silvie","email":"smedhurst2p@naver.com","gender":"Female","location":"Russia"},
    {"id":99,"name":"Oliver","email":"omarion2q@apache.org","gender":"Male","location":"Japan"},
    {"id":100,"name":"Enrique","email":"eeisikowitz2r@cisco.com","gender":"Male","location":"Sweden"}]

    var mCount=0
var fCount=0
for( user of users){
    if(user.gender =="Male"){
        mCount++
    }
    else{
        fCount++
    }
}
console.log("No of Male Users: ", mCount)
console.log("No of FeMale Users: ", fCount)

console.log(users.length)